### ISSUE TITLE
建议:主题代码颜色支持下高亮

### ISSUE THREAD

**Issue by ShallowLone** [SpeedyOrc-C/Allogenes-VSCode-Theme#2]
感觉光这个主题coding确实好看,但说实在还是要个代码高亮比较好,函数啥的纯加粗也够呛(o_0)

**Comment by SpeedyOrc-C** [comment]
> 感觉光这个主题coding确实好看,但说实在还是要个代码高亮比较好,函数啥的纯加粗也够呛(o_0)

感觉游戏里的用到的颜色并不是很多，字改成彩色之后感觉会不太搭。您觉得用什么颜色比较好看？

**Comment by ShallowLone** [comment]
既然都用了金色和蓝色（但是我感觉像黑色😂）
其实可以考虑高亮也是用深蓝色比较好
我最近也在进行调试，回头出结果了我再说下

**Comment by monicfenga** [comment]
可以参考一下gruvbox或solarized配色（浅色的）

还可以参考：
- https://github.com/a5hk/paper
- https://zhuanlan.zhihu.com/p/578376053

**Comment by SpeedyOrc-C** [comment]
这样如何？
<img width="582" alt="image" src="https://user-images.githubusercontent.com/40349377/226317778-532216f0-a512-41ab-a9d6-123ebdafb09d.png">

**Comment by monicfenga** [comment]
不错 👍

**Comment by ShallowLone** [comment]
可以Release了2333
这颜色其实可以的
（前几天试问了下ChatGpt给的是以下推荐颜色：深蓝色，翠绿，深紫，暗橙，感觉也还行）

**Comment by SpeedyOrc-C** [comment]
好纠结啊，看了一下其他的语言，不同的语言会把颜色安在不同的地方……

**Comment by SpeedyOrc-C** [comment]
CSS
<img width="387" alt="image" src="https://user-images.githubusercontent.com/40349377/226322587-7f11779c-ec52-48b3-8bc8-fc93c22afb23.png">

**Comment by SpeedyOrc-C** [comment]
已经发布了。
